# Generated by Django 5.1.3 on 2024-11-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nro_doc', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(choices=[('CC', 'cedula de ciudadania'), ('CE', 'cedula de Extranjeria'), ('TI', 'Tarjeta de identidad'), ('RC', 'Registro civil'), ('PA', 'Pasaporte'), ('ASI', 'Adulto sin identificaion'), ('MSI', 'Menor sin identificaion')], max_length=3)),
                ('lugar_exp_doc', models.CharField(max_length=50)),
                ('fecha_exp_doc', models.DateField()),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=30)),
                ('apellido_2', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo'), ('Union Libre', 'Union Libre'), ('Separado', 'Separado')], max_length=15)),
                ('email', models.EmailField(max_length=80)),
                ('telefono', models.CharField(max_length=15)),
                ('nacionalidad', models.CharField(max_length=30)),
            ],
        ),
    ]
